#!/usr/bin/ruby
puts({
'seijinnotou'=>'Beridzebeth',
'thesamplingparadise'=>'Mamonis',
'scharfrichter'=>'Ashemu',
'intheblackestden'=>'Bulluvegola',
'todestrieb'=>'Rche',
'nnrt'=>'Levaslater',
'thelimbo'=>'STN',
'yaksha'=>'Neulakyussra',
'tenkuunoyoake'=>'Cuvelia'
}[gets.chomp])