#!/usr/bin/node
// Generated by CoffeeScript 1.3.1 (minified manually)
(function(){
	var a=[],ma,mi,n=0,s,stdin;
	stdin=process.openStdin();
	stdin.setEncoding('utf8');

	var input_fragment="";
	stdin.on('data', function(input) {
			var ref=(input_fragment+input).split("\n");
			input_fragment=ref.pop();
			for(var i=0;i<ref.length;i++){
				if(ref[i]=='')continue;
				a.push(parseInt(ref[i]));
			}
	});

	stdin.on('end', function(z) {
		if(input_fragment){
			var ref=(input_fragment+"\n").split("\n");
			input_fragment=ref.pop();
			for(var i=0;i<ref.length;i++){
				if(ref[i]=='')continue;
				a.push(parseInt(ref[i]));
			}
		}
		var i,m;
		n=0;
		while(true){
			m=a[n];
			if(m==0)process.exit();
			s=0;ma=0;mi=1000;
			for(i=n+1;i<=n+m;i++){
				s=s+a[i];
				if(ma<a[i])ma=a[i];
				if(mi>a[i])mi=a[i];
			}
			console.log(Math.floor((s-ma-mi)/(m-2)));
			n=n+m+1;
		}
	});
})()