#include <string>
void test(const std::string &input, const std::string &expect);
void testloader(){ //insert test cases here
/*0*/ test( "YokoHamarb", "acdfp" );    
/*1*/ test( "Ruby", "twx" );    
/*2*/ test( "ruby", "nst" );    
/*3*/ test( "PHP", "gkluv" );    
/*4*/ test( "a", "bfg" );    
/*5*/ test( "b", "acfgh" );    
/*6*/ test( "m", "ghilnqrs" );    
/*7*/ test( "mg", "bcdhilmq" );    
/*8*/ test( "Mg", "fhiklmpq" );    
/*9*/ test( "MS", "ijmnoqrt" );    
/*10*/ test( "mG", "bcdhilmq" );    
/*11*/ test( "lf", "abcghklp" );    
/*12*/ test( "paq", "lprvw" );    
/*13*/ test( "bFH", "abcfg" );    
/*14*/ test( "Agh", "abcfgklm" );    
/*15*/ test( "Msul", "pruvw" );    
/*16*/ test( "RSRX", "jorty" );    
/*17*/ test( "xTsn", "ijmos" );    
/*18*/ test( "FHwnQ", "lmorsvwx" );    
/*19*/ test( "jIDIb", "cfghilmo" );    
/*20*/ test( "rLGPq", "ilmnprvx" );    
/*21*/ test( "WRiFhd", "ceg" );    
/*22*/ test( "gkfLfh", "cfglmpqr" );    
/*23*/ test( "STydYQ", "hklmpruv" );    
/*24*/ test( "spaeAWJ", "cdehimns" );    
/*25*/ test( "xTxTXwY", "mwx" );    
/*26*/ test( "xyQMkMi", "cdejlnow" );    
/*27*/ test( "HJkxpWxA", "cdhkp" );    
/*28*/ test( "hgaGDodg", "djo" );    
/*29*/ test( "abKBmkBc", "bdfik" );    
/*30*/ test( "mCvlhnilm", "adfgikqr" );    
/*31*/ test( "StyxTYsIh", "imnostxy" );    
/*32*/ test( "HLHnhLMLC", "ahlmn" );    
/*33*/ test( "DuHmbFQysI", "ehj" );    
/*34*/ test( "cGfGCaLgCq", "acguv" );    
/*35*/ test( "OisYOrOXwq", "ilnstvwx" );    
/*36*/ test( "wMnYIukHAvO", "bdefhjmn" );    
/*37*/ test( "HCfBhKHkhDF", "abdghikn" );    
/*38*/ test( "pUPmwrHsYSH", "morsy" );    
/*39*/ test( "PnCYYWnPoUxq", "bfopv" );    
/*40*/ test( "DiojiYXowowr", "cilmnstw" );    
/*41*/ test( "HLNsiNMnbAnn", "abdkm" );
}
