m[14][14];main(x,y,s,M){
	for(;~scanf("%d,%d,%d",&x,&y,&s);){
		m[x+2][y+2]++;m[x+1][y+2]++,m[x+3][y+2]++,m[x+2][y+1]++,m[x+2][y+3]++;
		if(s>1)m[x+1][y+1]++,m[x+3][y+1]++,m[x+1][y+3]++,m[x+3][y+3]++;
		if(s>2)m[x][y+2]++,m[x+4][y+2]++,m[x+2][y]++,m[x+2][y+4]++;
	}
	for(s=M=0,x=2;x<12;x++)for(y=2;y<12;M=M>m[x][y]?M:m[x][y],y++)if(!m[x][y])s++;
	printf("%d\n%d\n",s,M);
	exit(0);
}