#!/bin/sh
wget -O 01.zip http://yukicoder.me/problems/17/testcase.zip
wget -O 02.zip http://yukicoder.me/problems/18/testcase.zip
wget -O 03.zip http://yukicoder.me/problems/11/testcase.zip
wget -O 04.zip http://yukicoder.me/problems/19/testcase.zip
wget -O 05.zip http://yukicoder.me/problems/14/testcase.zip
wget -O 06.zip http://yukicoder.me/problems/24/testcase.zip
wget -O 07.zip http://yukicoder.me/problems/25/testcase.zip
wget -O 08.zip http://yukicoder.me/problems/26/testcase.zip
wget -O 09.zip http://yukicoder.me/problems/28/testcase.zip
wget -O 10.zip http://yukicoder.me/problems/29/testcase.zip
wget -O 11.zip http://yukicoder.me/problems/30/testcase.zip
wget -O 12.zip http://yukicoder.me/problems/34/testcase.zip
wget -O 13.zip http://yukicoder.me/problems/37/testcase.zip
wget -O 14.zip http://yukicoder.me/problems/38/testcase.zip
wget -O 15.zip http://yukicoder.me/problems/39/testcase.zip
wget -O 16.zip http://yukicoder.me/problems/42/testcase.zip
wget -O 17.zip http://yukicoder.me/problems/61/testcase.zip
wget -O 18.zip http://yukicoder.me/problems/59/testcase.zip
wget -O 19.zip http://yukicoder.me/problems/62/testcase.zip
wget -O 20.zip http://yukicoder.me/problems/64/testcase.zip