#!/usr/bin/ruby
gets.to_i.times{
s=gets.chomp
100.times{
s.gsub!('IIIII','V')
s.gsub!('XXXXX','L')
s.gsub!('CCCCC','D')
s.gsub!('VV','X')
s.gsub!('LL','C')
s.gsub!('DD','M')
s.gsub!('IIII','IV')
s.gsub!('XXXX','XL')
s.gsub!('CCCC','CD')
s.gsub!('VIV','IX')
s.gsub!('LXL','XC')
s.gsub!('DCD','CM')
}
puts s
}