#!/usr/bin/ruby
t='C:CPP:JAVA:PYTHON:PERL:PHP:RUBY:CSHARP:HASKELL:CLOJURE:BASH:SCALA:ERLANG:CLISP:LUA:BRAINFUCK:JAVASCRIPT:GO:D:OCAML:R:PASCAL:SBCL:DART:GROOVY:OBJECTIVEC'.split(':')
gets.to_i.times{
	puts t.include?(gets.chomp.split[1]) ? 'VALID' : 'INVALID'
}